#!/bin/bash

## This script is very self explanatory. It goes into my builds
## directory (which is where I keep my AUR installs) and goes
## into each directory to update it

builtin cd $HOME/builds
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
builtin cd $HOME/builds
for REPO in *; do
	builtin cd $REPO
	echo $REPO
	git reset --hard
	STATUS=$(git pull)
	if [[ $STATUS != *"Already up to date."* ]]; then
		echo "Updating..."
		git fetch origin
		git reset --hard origin/master
		makepkg -si --noconfirm
	else
		echo "Already up to date."
	fi
	cd ..
done
IFS=$SAVEIFS
