#!/bin/bash

## This script is very self explanatory. It goes into my builds
## directory (which is where I keep my AUR installs) and uses
## the output of 'dir' to go into each install and update it

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
cd $HOME/builds
for REPO in $(dir -Q1); do
	cd $REPO
	echo $REPO
	git reset --hard
	STATUS=$(git pull)
	if [[ $STATUS != *"Already up to date."* ]]; then
		echo "Updating..."
		makepkg -si --noconfirm
	else
		echo "Already up to date."
	fi
	cd ..
done
IFS=$SAVEIFS
