#!/bin/bash

#I wrote this because I wanted to have more fine
#control over the exact brightnes of my laptop
#screen, as the default brightness adjustment
#didn't offer small enough brightness intervals
#and doesn't go below a fairly high threshold

FILE="/sys/class/backlight/intel_backlight/brightness"
BRIGHT=$(cat $FILE)
MAX=976

case $1 in

	up)
		BRIGHT=$(($BRIGHT+60))
		;;

	down)
		BRIGHT=$(($BRIGHT-60))
		;;

	smup)
		BRIGHT=$(($BRIGHT+1))
		;;

	smdown)
		BRIGHT=$(($BRIGHT-1))
		;;

esac

[ $BRIGHT -gt $MAX ] && BRIGHT=$MAX
[ $BRIGHT -lt 0 ] && BRIGHT=0

sudo echo $BRIGHT > $FILE
