#!/usr/bin/env python3

#this script serves as the input gathering and sanitizing
#for the dl_items function over in drive_handling.py

import os
import sys
import drive_handling

SCOPE = ['https://www.googleapis.com/auth/drive']
start_dir = '/home/dromansk/Documents'
os.chdir(start_dir)
if os.path.exists('instruments') == False:
	os.mkdir('instruments')
os.chdir('instruments')

def user_input():
	print("Enter name of folder to download")
	dl_fold = input()
	return dl_fold

if len(sys.argv) < 2:
	dl_set = [user_input()]
else:
	dl_set = sys.argv[1:]
drive = drive_handling.drive_setup(SCOPES=SCOPE, token_dir=start_dir)
for item in dl_set:
	pwd = os.getcwd()
	if os.path.exists(item) == False:
		os.mkdir(item)
	os.chdir(item)
	drive_handling.dl_items(drive, item)
	os.chdir(pwd)
