#!/bin/bash

#when I was flashing magisk bootloaders onto my phone,
#I wrote this tto simplify the flashing process
#adb pull /sdcard/Download/magisk_patched.img

DIR="$HOME/Documents/android/"
BL=${2:-"magisk_patched"}

adb reboot bootloader
case $1 in

	boot)
		fastboot boot $DIR/$BL.img
		;;

	flash)
		fastboot flash boot $DIR$BL.img
		fastboot boot $DIR$BL.img
		;;

	*)
		echo "usage: droid [boot | flash]"
		;;

esac
