#!/bin/bash

# This is a temporary script while I convert all my local repos over to the new
# username and associated remote url

NEW="$(git remote get-url origin | sed 's/bigdiggysquiggle/dylan-romansky/')"
git remote set-url origin "$NEW"
