#!/bin/bash

# because I'm constructing the session's i3config from a
# base config file, a stored variable informing us what
# lines to comment out, and an extras file concatonated
# onto the end of the base config, I need a way to save
# any and all changes I make to the session's config so
# they will remain persistent into the next session

# make a backup of our current configuration so we have
# something to diff against for changes
builtin cd $HOME/.config/i3
source ./.i3vars
cp config oldconf
i3-setup.sh
# check if there's been an external update to the source
# configuration files and if so, perform the rest of the
# script before letting the user input further changes
DIFFS="$(sdiff -l config oldconf | cat -n | grep -v -e '($')"
if [ -z "$DIFFS" ]; then
    vim oldconf
else
	echo "Unresolved changes detected. Resolving."
	echo "If you still want to make changes, please run this script again after completion."
fi

# check if there are any differences and thus if we need
# to update our variables
DIFFS="$(sdiff -l config oldconf | cat -n | grep -v -e '($')"
if [ -z "$DIFFS" ]; then
	echo "no update necessary"
	rm oldconf
	exit
fi

# get linecount of main config so it can be updated if needed
MAINLC=$(wc -l .mainconf | awk '{ print $1 }')

# create the list of new lines and whether they're being
# added or commented out
NEWLINES=()
while read LINE; do
	NEWLINES+=("$LINE")
done <<< $(echo "$DIFFS")

# create a new array housing all the lines that get commented
# out when concatonating the base config and extra config to
# make the sessions' i3config
# also add/remove any new lines created/deleted during this
# session to the base and extra configs as needed

i=0
j=0
for EACH in "${NEWLINES[@]}"; do
	NEWLINE=$(echo "$EACH" | awk '{ print $1 }')
    echo "Line $NEWLINE"
    echo "i $i j $j"
    while [ -n "$i3LINES" ] && [ $(($i3LINES+$i-$j)) -lt $(($NEWLINE-$j)) ]; do
        NEWARR+=($(($i3LINES+$i-$j)))
		i3LINES=("${i3LINES[@]:1}")
	done
	case "${NEWLINES[0]}" in
		*'>'*) # append
            echo "Append"
			NEWCONF=$(sed -n "$NEWLINE{p;q}" oldconf)
            if [ $MAINLC -ge $(($NEWLINE-$j)) ]; then
                sed -i --follow-symlinks "$(($NEWLINE-$j)) i $NEWCONF" .mainconf
			else
                echo "$MAINLC $NEWLINE $j"
                echo "$(($NEWLINE-$j))"
                sed -i --follow-symlinks "$(($NEWLINE-$MAINLC-$j)) i $NEWCONF" .extraconf
			fi
			i=$(($i+1))
			;;
		*'<'*) # remove
            if [ $MAINLC -ge $(($NEWLINE-$j)) ]; then
                echo "nope"
                sed -i --follow-symlinks "$(($NEWLINE-$j)) d" .mainconf
			else
                echo "yup"
				sed -i --follow-symlinks "$(($NEWLINE-$MAINLC-$j))d" .extraconf
			fi
			j=$(($j+1))
			;;
		*'|'*)
            echo "Default"
			FIELD2=$(sed "$(($NEWLINE-$j))q;d" oldconf)
			echo "$FIELD2"
			if [[ "$FIELD2" =~ ^[:space:]*# ]]; then
                echo "remove commentation"
				CURRNUM=$(($NEWLINE-$j))
				NEWARR+=("$CURRNUM")
                FIELD2=$(echo $FIELD2 | sed 's|#||1')
			else
                echo "remove entry if needed"
				for (( k=0; k<=${#i3LINES[@]}; k++ )); do
                    echo "$(($NEWLINE-$j)) == $((${i3LINES[$k]}))"
                    if [ $(($NEWLINE-$j)) -eq $((${i3LINES[$k]}+$i)) ]; then
                        echo "unset"
						i3LINES=( "${i3LINES[@]:0:$k}" "${i3LINES[@]:$(($k+1))}" )
						break
					fi
				done
			fi
            echo "$MAINLC $j $NEWLINE"
			if [ $MAINLC -ge $NEWLINE ]; then
				sed -i --follow-symlinks ''"$(($NEWLINE-$j))"'s|.*|'"$FIELD2"'|' .mainconf
			else
				sed -i --follow-symlinks ''"$(($NEWLINE-$MAINLC-$j))"'s|.*|'"$FIELD2"'|' .extraconf
			fi
			;;
	esac
	NEWLINES=("${NEWLINES[@]:1}")
done
for LEFTOVER in "${i3LINES[@]}"; do
	NEWARR+=($(($i+$LEFTOVER-$j)))
done
echo "NEWARR ${NEWARR[@]}"

# finally output the list of modified lines and clean up
sed -i --follow-symlinks 's|'"export i3LINES=.*"'|'"export\ i3LINES=(${NEWARR[*]})"'|' .i3vars
rm oldconf
i3restart
