#!/usr/bin/python

#this isn't a script that I wrote, if you recognize this
#script please let me know so I can give proper credit.

#this script locates the next blank i3 workspace and brings
#you to it

import json, subprocess

output = subprocess.check_output(['i3-msg', '-t', 'get_workspaces'])
workspaces = json.loads(output)

next_num = next(i for i in range(1, 100) if not [ws for ws in workspaces if ws['num'] == i])

subprocess.call(['i3-msg', 'workspace number %i' % next_num])
