#!/bin/bash

#next time pip has an error, check to see if it left an exit code.
#if it did, have this use python -m ensurepip --upgrade
#pip install -U $(pip freeze | awk '{split($0, a, "=="); print a[1]}')
python3 -m pip list --outdated --format=json | jq -r '.[] | "\(.name)==\(.latest_version)"' | xargs -n1 pip3 install -U
if [ $? -ne 0 ]; then
	python -m ensurepip --upgrade
fi
#pip install -U $(pip freeze | awk '{split($0, a, "=="); print a[1]}')
