#!/bin/bash
#sometimes the network card in my laptop starts choking on
#longer downloads. this script forces it to complete the
#update or die trying

sudo pacman -Syu --noconfirm
while [ $? -ne 0 ]; do
	sudo pacman -Syu --noconfirm
done
