#!/bin/bash

SUM=$(md5sum "$HOME/resume draft.docx")
OSUM=$(cat "$HOME/resume draft.md5")
echo "$SUM" "|" "$OSUM"
if [[ $SUM != "$OSUM" ]]; then
	FILES+=("$HOME/resume draft.docx")
	echo "$SUM" > "$HOME/resume draft.md5"
fi
SUM=$(md5sum "$HOME/cover_letter.docx")
OSUM=$(cat "$HOME/cover_letter.md5")
echo "$SUM" "|" "$OSUM"
if [[ $SUM != "$OSUM" ]]; then
	FILES+=("$HOME/cover_letter.docx")
	echo "$SUM" > "$HOME/cover_letter.md5"
fi
if [ -n "$FILES" ]; then
    echo "uploading ${FILES[*]}"
	uploader "resume and cover letters" "${FILES[@]}"
fi
