#!/bin/bash

# This script checks to see if I've updated my resume or my
# cover letter. If it detects changes, it uploads the changed
# file to my google drive

SUM=$(md5sum "$HOME/resume draft.docx")
OSUM=$(cat "$HOME/resume draft.md5")
echo "$SUM" "|" "$OSUM"
if [[ $SUM != "$OSUM" ]]; then
	UL=true
	echo "$SUM" > "$HOME/resume draft.md5"
fi
SUM=$(md5sum "$HOME/cover_letter.docx")
OSUM=$(cat "$HOME/cover_letter.md5")
echo "$SUM" "|" "$OSUM"
if [[ $SUM != "$OSUM" ]]; then
	UL=true
	echo "$SUM" > "$HOME/cover_letter.md5"
fi
if [ "$UL" = true ]; then
    echo "uploading"
	uploader "resume and cover letters" "resume draft.docx" "cover_letter.docx"
else
	echo "files are up to date
fi
