#!/bin/bash

#this script allows me to use keybindings in i3 to control the
#volume and microphone levels of my system. It still has some
#issues because I'm still learning how sound routing works in
#a "build it yourself" environment

#convert this to use font-awesome volume icons
function noty {
	killall notify-osd
	case $1 in

		Volume)
			sendstr="$1: $(pactl get-sink-volume @DEFAULT_SINK@ | awk 'FNR==1{ print $5 }')"
			if [[ "$(pactl list sinks | grep Mute)" == *"yes"* ]]; then
				sendstr+=" (Mute)"
			fi
			notify-send "$sendstr"
			;;

		Mic)
			notify-send "$1: $(pactl get-source-volume @DEFAULT_SOURCE@ | awk 'FNR==1{ print $5 }')"
			;;
	esac
	pkill -SIGRTMIN+1 i3blocks #so that i3blocks knows to update its audio block
}

case $1 in

	up)
		pactl set-sink-volume @DEFAULT_SINK@ +10%
		noty Volume
		;;

	down)
		pactl set-sink-volume @DEFAULT_SINK@ -10%
		noty Volume
		;;

	smup)
		pactl set-sink-volume @DEFAULT_SINK@ +5%
		noty Volume
		;;

	smdown)
		pactl set-sink-volume @DEFAULT_SINK@ -5%
		noty Volume
		;;

	micup)
		pactl set-source-volume @DEFAULT_SOURCE@ +10%
		noty Mic
		;;

	micdown)
		pactl set-source-volume @DEFAULT_SOURCE@ -10%
		noty Mic
		;;

	smicup)
		pactl set-source-volume @DEFAULT_SOURCE@ +5%
		noty Mic
		;;

	smicdown)
		pactl set-source-volume @DEFAULT_SOURCE@ -5%
		noty Mic
		;;

	mute)
		pactl set-sink-mute @DEFAULT_SINK@ toggle
		killall notify-osd
		if [[ "$(pactl list sinks | grep Mute)" == *"yes"* ]]; then
			notify-send "Volume: Mute"
		else
			notify-send "Volume: Unmute"
		fi
		;;
esac
pkill -SIGRTMIN+1 i3blocks #so i3blocks knows to update its volume block
